### PR TITLE
MockServerClient null / empty body regression fix

### LINKED ISSUE #2763: [BUG] MockServerClient null / empty body regression
Tapir version: 1.+

Scala version: 2 / 3

`whenInputMatches` with a `null` / `None` body set as the expectation, it fails at runtime due to the mismatch of the generated json to the expected mock server schema. 

```scala
mockServerClient.whenInputMatches(...)((), None)
```

The produced error may look like:

```scala
[info] - should match json null body *** FAILED *** (37 milliseconds)
[info]   Failure(sttp.tapir.server.mockserver.MockServerException$IncorrectRequestFormat: Failed to interact with mock server: incorrect request format incorrect expectation json format for:
[info]
[info]     {
[info]       "httpRequest" : {
[info]         "method" : "GET",
[info]         "path" : "/api/v1/order",
[info]         "body" : null,
[info]         "headers" : {
[info]           "Accept-Encoding" : [ "gzip, deflate" ]
[info]         }
[info]       },
[info]       "httpResponse" : {
[info]         "statusCode" : 200,
[info]         "body" : {
[info]           "json" : {
[info]             "id" : "fa9e3a9e-2af3-4b16-a1de-461a4aa62452",
[info]             "name" : "John"
[info]           },
[info]           "matchType" : "STRICT",
[info]           "type" : "JSON"
[info]         },
[info]         "headers" : {
[info]           "Content-Type" : [ "application/json" ]
[info]         }
[info]       }
[info]     }
[info]
[info]    schema validation errors:
[info]
[info]     2 errors:
[info]      - $.httpRequest.body: should match one of its valid types: {
[info]          "title": "request body matcher",
[info]          "anyOf": [
[info]            {
[info]              "type": "object",
[info]              "additionalProperties": false,
[info]              "properties": {
[info]                "not": {
[info]                  "type": "boolean"
[info]                },
[info]                "type": {
[info]                  "enum": [
[info]                    "BINARY"
[info]                  ]
[info]                },
[info]                "base64Bytes": {
[info]                  "type": "string"
[info]                },
[info]                "contentType": {
[info]                  "type": "string"
[info]                }
[info]              }
[info]            },
[info]            {
[info]              "type": "object",
[info]              "additionalProperties": false,
[info]              "properties": {
[info]                "not": {
[info]                  "type": "boolean"
[info]                },
[info]                "type": {
[info]                  "enum": [
[info]                    "JSON"
[info]                  ]
[info]                },
[info]                "json": {
[info]                  "type": "string"
[info]                },
[info]                "contentType": {
[info]                  "type": "string"
[info]                },
[info]                "matchType": {
[info]                  "enum": [
[info]                    "STRICT",
[info]                    "ONLY_MATCHING_FIELDS"
[info]                  ]
[info]                }
[info]              }
[info]            },
[info]            {
[info]              "type": "object",
[info]              "additionalProperties": true
[info]            },
[info]            {
[info]              "type": "array",
[info]              "additionalProperties": true
[info]            },
[info]            {
[info]              "type": "object",
[info]              "additionalProperties": false,
[info]              "properties": {
[info]                "not": {
[info]                  "type": "boolean"
[info]                },
[info]                "type": {
[info]                  "enum": [
[info]                    "JSON_SCHEMA"
[info]                  ]
[info]                },
[info]                "jsonSchema": {
[info]                  "oneOf": [
[info]                    {
[info]                      "type": "string"
[info]                    },
[info]                    {
[info]                      "$ref": "http://json-schema.org/draft-07/schema"
[info]                    }
[info]                  ]
[info]                }
[info]              }
[info]            },
[info]            {
[info]              "type": "object",
[info]              "additionalProperties": false,
[info]              "properties": {
[info]                "not": {
[info]                  "type": "boolean"
[info]                },
[info]                "type": {
[info]                  "enum": [
[info]                    "JSON_PATH"
[info]                  ]
[info]                },
[info]                "jsonPath": {
[info]                  "type": "string"
[info]                }
[info]              }
[info]            },
[info]            {
[info]              "type": "object",
[info]              "additionalProperties": false,
[info]              "properties": {
[info]                "not": {
[info]                  "type": "boolean"
[info]                },
[info]                "type": {
[info]                  "enum": [
[info]                    "PARAMETERS"
[info]                  ]
[info]                },
[info]                "parameters": {
[info]                  "$ref": "#/definitions/keyToMultiValue"
[info]                }
[info]              }
[info]            },
[info]            {
[info]              "type": "object",
[info]              "additionalProperties": false,
[info]              "properties": {
[info]                "not": {
[info]                  "type": "boolean"
[info]                },
[info]                "type": {
[info]                  "enum": [
[info]                    "REGEX"
[info]                  ]
[info]                },
[info]                "regex": {
[info]                  "type": "string"
[info]                }
[info]              }
[info]            },
[info]            {
[info]              "type": "object",
[info]              "additionalProperties": false,
[info]              "properties": {
[info]                "not": {
[info]                  "type": "boolean"
[info]                },
[info]                "type": {
[info]                  "enum": [
[info]                    "STRING"
[info]                  ]
[info]                },
[info]                "string": {
[info]                  "type": "string"
[info]                },
[info]                "subString": {
[info]                  "type": "boolean"
[info]                },
[info]                "contentType": {
[info]                  "type": "string"
[info]                }
[info]              }
[info]            },
[info]            {
[info]              "type": "string"
[info]            },
[info]            {
[info]              "type": "object",
[info]              "additionalProperties": false,
[info]              "properties": {
[info]                "not": {
[info]                  "type": "boolean"
[info]                },
[info]                "type": {
[info]                  "enum": [
[info]                    "XML"
[info]                  ]
[info]                },
[info]                "xml": {
[info]                  "type": "string"
[info]                },
[info]                "contentType": {
[info]                  "type": "string"
[info]                }
[info]              }
[info]            },
[info]            {
[info]              "type": "object",
[info]              "additionalProperties": false,
[info]              "properties": {
[info]                "not": {
[info]                  "type": "boolean"
[info]                },
[info]                "type": {
[info]                  "enum": [
[info]                    "XML_SCHEMA"
[info]                  ]
[info]                },
[info]                "xmlSchema": {
[info]                  "type": "string"
[info]                }
[info]              }
[info]            },
[info]            {
[info]              "type": "object",
[info]              "additionalProperties": false,
[info]              "properties": {
[info]                "not": {
[info]                  "type": "boolean"
[info]                },
[info]                "type": {
[info]                  "enum": [
[info]                    "XPATH"
[info]                  ]
[info]                },
[info]                "xpath": {
[info]                  "type": "string"
[info]                }
[info]              }
[info]            }
[info]          ]
[info]        }
[info]      - $.httpRequest.specUrlOrPayload: is missing, but is required, if specifying OpenAPI request matcher
[info]
[info]     OpenAPI Specification: https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.15.x
[info]     Documentation: https://mock-server.com/mock_server/creating_expectations.html) did not equal Success(Value(Right(OrderCreatedEvent("fa9e3a9e-2af3-4b16-a1de-461a4aa62452", "John", None)))) (SttpMockServerClientSpec.scala:218)
```

To Reproduce: https://github.com/pomadchin/tapir/commit/ad8fa9082ecff3abc842e2bcc426a97ac13b5dc4

```scala
// SttpMockServerClientSpec.scala

  it should "match json null body" in {
    import TapirJsonCirceWithDropNullEnabled.jsonBody

    val orderEndpoint = endpoint
      .in("api" / "v1" / "order")
      .get
      .errorOut(jsonBody[ApiError])
      .out(jsonBody[OrderCreatedEvent])

    val sampleOut = OrderCreatedEvent(id = uuid(), name = "John", total = None)

    val actual = for {
      _ <- mockServerClient
        .whenInputMatches(orderEndpoint)((), None)
        .thenSuccess(sampleOut)

      resp <- SttpClientInterpreter()
        .toRequest(orderEndpoint, baseUri = Some(baseUri))
        .apply(None)
        .send(backend)

      _ <- mockServerClient
        .verifyRequest(orderEndpoint, VerificationTimes.exactlyOnce)((), None)
    } yield resp.body

    actual shouldEqual Success(Value(Right(sampleOut)))
  }
```

This is a regression intorduced by the https://github.com/softwaremill/tapir/issues/2128 fix:

https://github.com/softwaremill/tapir/blob/aa97ec55fd0192258cceb538c12f43f202ade2db/server/sttp-mock-server/src/main/scala/sttp/tapir/server/mockserver/SttpMockServerClient.scala#L209

Apparently, the `httpRequest.body` can't be null but can be dropped if null, otherwise it breaks the json schema validation.

The proper solution is to drop nulls in the expectation request, but not in the user body. i.e. so if the user body contains nulls we don't drop them, but if any non user field in the expectation request is null we have to drop it, otherwise the request is not aligned with the expected schema.

### PR DESCRIPTION
**Pull request by pomadchin**
A low effort attempt to fix #2763 also trying not to invade the whole code base. Let me know if that's not sufficient enough / not really a desired approach, since we could try to come up with smth more radical.

Closes #2763

### CODE REVIEW

File: server/sttp-mock-server/src/main/scala/sttp/tapir/server/mockserver/impl/JsonCodecs.scala [hunk 1]
```diff
@@ -81,12 +81,30 @@ private[mockserver] object JsonCodecs {
       }
   }
 
-  private implicit val expectationRequestDefinitionCodec: Codec[ExpectationRequestDefinition] = deriveCodec[ExpectationRequestDefinition]
-  private implicit val expectationResponseDefinitionCodec: Codec[ExpectationResponseDefinition] = deriveCodec[ExpectationResponseDefinition]
-  private implicit val expectationTimesCodec: Codec[ExpectationTimes] = deriveCodec[ExpectationTimes]
-  private implicit val expectationTimeToLiveCodec: Codec[ExpectationTimeToLive] = deriveCodec[ExpectationTimeToLive]
+  private def deriveCodecDropNull[T](implicit encoder: Encoder[T], decoder: Decoder[T]): Codec[T] =
+    Codec.from(decoder, encoder.mapJson(_.dropNullValues))
```
Comment (pomadchin) [inline server/sttp-mock-server/src/main/scala/sttp/tapir/server/mockserver/impl/JsonCodecs.scala:85]: Drop nulls _non recursively_.

File: server/sttp-mock-server/src/test/scala/sttp/tapir/server/mockserver/SttpMockServerClientSpec.scala [hunk 2]
```diff
@@ -190,5 +190,33 @@ class SttpMockServerClientSpec extends AnyFlatSpec with Matchers with BeforeAndA
...
+      .in("api" / "v1" / "order")
+      .get
+      .errorOut(jsonBody[ApiError])
+      .out(jsonBody[OrderCreatedEvent])
+
+    val sampleOut = OrderCreatedEvent(id = uuid(), name = "John", total = None)
+
+    val actual = for {
+      _ <- mockServerClient
+        .whenInputMatches(orderEndpoint)((), None)
```
Comment (adamw) [inline server/sttp-mock-server/src/test/scala/sttp/tapir/server/mockserver/SttpMockServerClientSpec.scala:206]: shouldn't this `None` be a `()`? There are compilation warnings with this form

File: server/sttp-mock-server/src/main/scala/sttp/tapir/server/mockserver/impl/JsonCodecs.scala [hunk 3]
```diff
@@ -81,12 +83,17 @@ private[mockserver] object JsonCodecs {
       }
   }
 
-  private implicit val expectationRequestDefinitionCodec: Codec[ExpectationRequestDefinition] = deriveCodec[ExpectationRequestDefinition]
-  private implicit val expectationResponseDefinitionCodec: Codec[ExpectationResponseDefinition] = deriveCodec[ExpectationResponseDefinition]
-  private implicit val expectationTimesCodec: Codec[ExpectationTimes] = deriveCodec[ExpectationTimes]
-  private implicit val expectationTimeToLiveCodec: Codec[ExpectationTimeToLive] = deriveCodec[ExpectationTimeToLive]
+  private def deriveCodecDropNull[A](implicit codec: Lazy[DerivedAsObjectCodec[A]]): Codec[A] =
+    Codec.from(codec.value, codec.value.mapJson(_.dropNullValues))
```
Comment (adamw) [inline server/sttp-mock-server/src/main/scala/sttp/tapir/server/mockserver/impl/JsonCodecs.scala:87]: doesn't this fix re-introduce https://github.com/softwaremill/tapir/issues/2128 ?

Comment (adamw) [reply server/sttp-mock-server/src/main/scala/sttp/tapir/server/mockserver/impl/JsonCodecs.scala:87]: 🤦 ok I've read the code, that's a completely different thing. Looks good :)

Comment (pomadchin) [reply server/sttp-mock-server/src/main/scala/sttp/tapir/server/mockserver/impl/JsonCodecs.scala:87]: @adamw nope, all the tests pass; 

this one is intentionally non-recursive drop nulls, by the mockserver contract we need to drop nulls in the _request_ body in case there are nulls, but we don't want to drop nulls in the user body if it's not null;

So any httpRequest / httpResponse non recursive nulls should be dropped:

Invalid JSON: 

```js
{
  "httpRequest": {
    "method": "GET",
    "path": "/api/v1/order",
    "body": null, // we need to drop null if the body is null
    "headers": {
      "Accept-Encoding": [
        "gzip, deflate"
      ]
    }
  },
  "httpResponse": ...
}
```

Valid JSONs:

```js
{
  "httpRequest": {
    "method": "GET",
    "path": "/api/v1/order",
    "headers": {
      "Accept-Encoding": [
        "gzip, deflate"
      ]
    }
  },
  "httpResponse": ...
}
```

or 

```js
{
  "httpRequest": {
    "method": "GET",
    "path": "/api/v1/order",
    "body": { "field": null },
    "headers": {
      "Accept-Encoding": [
        "gzip, deflate"
      ]
    }
  },
  "httpResponse": ...
}
```

File: server/sttp-mock-server/src/test/scala/sttp/tapir/server/mockserver/SttpMockServerClientSpec.scala (hunk 2 above)
Comment (pomadchin) [reply server/sttp-mock-server/src/test/scala/sttp/tapir/server/mockserver/SttpMockServerClientSpec.scala]: Good catch, I didn't pay attention to that warning :+1:

Comment (pomadchin) [reply server/sttp-mock-server/src/test/scala/sttp/tapir/server/mockserver/SttpMockServerClientSpec.scala]: 48fb6e6
