### PR TITLE
[bugfix] Return raw ZIO response body where applicable

### LINKED ISSUE #3034: [BUG] tapir + zio-http is not logging response
Tapir version: 1.6.0

Scala version: 3.3.0

**Describe the bug**

Using tapir with zio-http, when configuring the `App` to log the body response with `RequestHandlerMiddlewares.requestLogging(logRequestBody = true, logResponseBody = true)` the response is not being logged:

```
[info] timestamp=2023-07-13T13:43:17.990517Z level=INFO thread=#zio-fiber-41 message="Http request served" location=TapirHttpServer.run file=TapirHttpServer.scala line=34 method=GET url=/body status_code=200 request_size=0 duration_ms=210 request=
```

**How to reproduce?**

```scala
import sttp.tapir.Schema
import zio.json.*

case class Foo(bar: String, baz: Int)
object Foo:
  given JsonCodec[Foo] = DeriveJsonCodec.gen
  given Schema[Foo] = Schema.derived[Foo]
```

tapir + zio-http
```scala
import sttp.tapir.json.zio.*
import sttp.tapir.server.ziohttp.ZioHttpInterpreter
import sttp.tapir.ztapir.*
import sttp.tapir.{PublicEndpoint, Schema}
import zio.*
import zio.http.{ endpoint as _, * }

object TapirHttpServer extends ZIOAppDefault:
  val body: PublicEndpoint[Unit, Unit, List[Foo], Any] =
    endpoint.get.in("body").out(jsonBody[List[Foo]])

  val app: HttpApp[Any, Throwable] =
    ZioHttpInterpreter().toHttp(
      body.zServerLogic(_ => ZIO.succeed(List(Foo("a", 1), Foo("b", 2), Foo("c", 3))))
    )

  override def run =
    val logConfig =
      RequestHandlerMiddlewares.requestLogging(logRequestBody = true, logResponseBody = true)

    Server
      .serve(app.withDefaultErrorResponse @@ logConfig)
      .provide(
        ZLayer.succeed(Server.Config.default.port(8080)),
        Server.live
      )
      .exitCode
```

only zio-http, for comparison
```scala
import zio.*
import zio.http.{ endpoint as _, * }

object ZioHttpServer extends ZIOAppDefault:
  val app: App[Any] =
    val logConfig =
      RequestHandlerMiddlewares.requestLogging(logRequestBody = true, logResponseBody = true)

    Http.collect[Request] { case Method.GET -> Root / "body" =>
      Response.json(List(Foo("a", 1), Foo("b", 2), Foo("c", 3)).toJson)
    } @@ logConfig

  override val run =
    Server.serve(app).provide(Server.default)
```

**Additional information**

https://softwaremill.community/t/tapir-zio-http-is-not-showing-the-response-in-the-logs/250

### PR DESCRIPTION
**Pull request by kciesielski**
Fixes #3034 

This PR changes handling of raw body types. Instead of always using a `ZStream`, such responses are packed into a `Chunk[Byte]`. This allows logging the response body by ` zio.http.internal.middlewares.RequestLogging`.

### CODE REVIEW

File: server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpResponseBody.scala [hunk 1]
```diff
@@ -0,0 +1,13 @@
+package sttp.tapir.server.ziohttp
+
+import zio.stream.ZStream
+import zio.Chunk
+
+private[ziohttp] sealed trait ZioHttpResponseBody {
+  def contentLength: Option[Long]
+}
+
+private[ziohttp] case class ZioStreamHttpResponseBody(stream: ZStream[Any, Throwable, Byte], val contentLength: Option[Long])
```
Comment (adamw) [inline server/zio-http-server/src/main/scala/sttp/tapir/server/ziohttp/ZioHttpResponseBody.scala:10]: [minor] is the `val` needed? it is a case class?

**Review by adamw — APPROVED** [review]
Looks good, thanks! :)
