### PR TITLE
3234: use markOptionsAsNullable for Option reference types

### LINKED ISSUE #3234: [BUG] markOptionsAsNullable doesn't work for reference types
Tapir version: 1.8.0

Scala version: 2.13.12

**Describe the bug**
`markOptionsAsNullable` doesn't work for `field: Option[A]` where A is not a primitive type, e.g. A is a class

What is the problem?

**How to reproduce?**
https://scastie.scala-lang.org/YJh2KhRjS5y0CNBkofZkkQ

image

**Expected**

image

### PR DESCRIPTION
**Pull request by eanea**
fixes #3234 

- inlines the reference type if `markOptionsAsNullable = true`

### CODE REVIEW

**Comment by adamw** [comment]
Could you maybe add a test? https://github.com/softwaremill/tapir/blob/68e643fcc2a40c9e6cb2b689d756849aab1dc6c7/docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala#L656 seems like a similar one

**Comment by eanea** [comment]
generated schema

image

**Comment by eanea** [comment]
> Could you maybe add a test?
> 
> https://github.com/softwaremill/tapir/blob/68e643fcc2a40c9e6cb2b689d756849aab1dc6c7/docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala#L656
> 
> seems like a similar one

done :)

File: docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala [hunk 1]
```diff
@@ -666,6 +666,20 @@ class VerifyYamlTest extends AnyFunSuite with Matchers {
     actualYamlNoIndent shouldBe expectedYaml
   }
 
+  test("should mark optional class fields as nullable by inlining them when configured to do so") {
+    case class Bar(bar: Int)
+    case class ClassWithOptionClassField(optionalIntField: Option[Bar], requiredStringField: String)
```
Comment (kciesielski) [inline docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala:671]: **nitpick:** `optionalObjField`

**Review by kciesielski — APPROVED** [review]

File: docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala (hunk 1 above)
Comment (eanea) [reply docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala]: yeah :) fixed it

File: docs/openapi-docs/src/test/resources/expected_nullable_option_class_field.yml [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+        bar:
+          type: integer
+          format: int32
+    ClassWithOptionClassField:
+      required:
+        - requiredStringField
+      type: object
+      properties:
+        optionalObjField:
+          required:
```
[the remark this answers is not in the document]
Comment (eanea) [reply docs/openapi-docs/src/test/resources/expected_nullable_option_class_field.yml:44]: it'll require changes in the `sttp-apispec` for all encoders.
I could do it for the `circe` integration only. will it be acceptable?

File: docs/openapi-docs/src/test/resources/expected_nullable_option_class_field.yml [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+          format: int32
+    ClassWithOptionClassField:
+      required:
+        - requiredStringField
+      type: object
+      properties:
+        optionalClassField:
+          oneOf:
+            - $ref: '#/components/schemas/Bar'
+            - type: 'null'
```
Comment (eanea) [inline docs/openapi-docs/src/test/resources/expected_nullable_option_class_field.yml:46]: `- type: 'null'` requires to merge & use https://github.com/softwaremill/sttp-apispec/pull/118

File: docs/openapi-docs/src/test/resources/expected_nullable_option_class_field.yml (hunk 2 above)
[the remark this answers is not in the document]
Comment (eanea) [reply docs/openapi-docs/src/test/resources/expected_nullable_option_class_field.yml]: - PR for `sttp-apispec` circe is ready https://github.com/softwaremill/sttp-apispec/pull/118
- updated current PR to generete `oneOf` instead of inlining

File: docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala [hunk 4]
```diff
@@ -26,7 +26,12 @@ private[schema] class TSchemaToASchema(toSchemaReference: ToSchemaReference, mar
       case TSchemaType.SArray(nested @ TSchema(_, Some(name), _, _, _, _, _, _, _, _, _)) =>
         ASchema(SchemaType.Array).copy(items = Some(toSchemaReference.map(nested, name)))
       case TSchemaType.SArray(el) => ASchema(SchemaType.Array).copy(items = Some(apply(el)))
-      case TSchemaType.SOption(nested @ TSchema(_, Some(name), _, _, _, _, _, _, _, _, _)) => toSchemaReference.map(nested, name)
+      case TSchemaType.SOption(nested @ TSchema(_, Some(name), _, _, _, _, _, _, _, _, _)) => {
+        val ref = toSchemaReference.map(nested, name)
+        if (!markOptionsAsNullable) ref
+        else
+          ASchema.oneOf(List(ref), ref.discriminator).copy(nullable = Some(true))
```
Comment (adamw) [inline docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala:33]: maybe doing here simply `ASchema.oneOf(List(ref, ASchema(SchemaType.Null), None)` would work?

Comment (adamw) [reply docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala]: I've added this change, let's see if things work :)

Comment (eanea) [reply docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala]: great! thank you :) 
what else is needed to merge the PR?

Comment (adamw) [reply docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala]: nothing, tests pass :)

Comment (adamw) [reply docs/apispec-docs/src/main/scala/sttp/tapir/docs/apispec/schema/TSchemaToASchema.scala]: thanks!
