### PR TITLE
Fixed descriptions for circe Json fields

### LINKED ISSUE #1378: The description of an Option[io.circe.Json] does not work.
I want to use `io.circe.Json` for wrapped values that have no case class representations.

This works for Seq but not for Option.

```
  case class ExampleMessageIn(
                               @description("The name of your example")
                               name: String,
                               @description("My seq that does work")
                               numbers: Seq[Json] = Seq(ch,li),
                               @description("My json is great but optional") // this line does not create a docu.
                               maybeJson: Option[Json] = Some(li),
                               @description("My optional string is working")
                               maybeString: Option[String] = Some("hello")
                             )
```
image

How to reproduce:

Run this code: https://gist.github.com/pme123/87b50f25e8f9ca7a6bccd27ee58d18c1

### PR DESCRIPTION
**Pull request by bartekzylinski**
closes #1378

### CODE REVIEW

File: docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala [hunk 1]
```diff
@@ -547,4 +547,19 @@ class VerifyYamlTest extends AnyFunSuite with Matchers {
     val actualYaml = OpenAPIDocsInterpreter().toOpenAPI(ep, "title", "1.0").toYaml
     noIndentation(actualYaml) shouldBe expectedYaml
   }
+
+  test("should contain description field for Option[Json] field") {
+    val expectedYaml = load("expected_type_and_description_for_circe_json.yml")
+
+    val myEndpoint = endpoint
+      .post
+      .in(jsonBody[ExampleMessageIn])
```
Comment (adamw) [inline docs/openapi-docs/src/test/scala/sttp/tapir/docs/openapi/VerifyYamlTest.scala:556]: it would be better to keep the example as self-contained as possible - maybe we can move the class over here and nest it inside the test?

File: json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala [hunk 2]
```diff
@@ -27,11 +27,11 @@ trait TapirJsonCirce {
 
   def jsonPrinter: Printer = Printer.noSpaces
 
-  // Json is a coproduct with unknown implementations
+  // Json is a product with unknown implementations
   implicit val schemaForCirceJson: Schema[Json] =
     Schema(
-      SCoproduct(Nil, None)(_ => None),
-      Some(SName("io.circe.Json"))
+      SProduct(Nil),
```
Comment (adamw) [inline json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala:33]: what about other json integrations? Play-json, json4s etc., I think they also contain schemas for arbitrary json values

Comment (adamw) [reply json/circe/src/main/scala/sttp/tapir/json/circe/TapirJsonCirce.scala:33]: on second though ... I'm not sure if `Product` is the right type here. A `Json` value can be an object OR a number OR a string etc. - hence the original mapping of `SCoproduct`, meaning that it can be anythng really. So - can we make it work with `SCoproduct`?

File: json/circe/src/test/scalajvm/sttp/tapir/json/circe/TapirJsonCirceTests.scala [hunk 3]
```diff
@@ -50,7 +50,7 @@ class TapirJsonCirceTests extends AnyFlatSpecLike with Matchers {
     error.underlying shouldBe a[DecodingFailure]
   }
 
-  it should "return a coproduct schema for a Json" in {
+  it should "return a product schema for a Json" in {
```
Comment (adamw) [inline json/circe/src/test/scalajvm/sttp/tapir/json/circe/TapirJsonCirceTests.scala:53]: coproduct :)
